version: '3'
services:
  blue:
    container_name: blue
    image: chahs1012/capstone
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
  green:
    container_name: green
    image: chahs1012/capstone
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul